README.md
=> Adds full stop :)

src/Redis.OM/Modeling/DateTimeJsonConverter.cs, src/Redis.OM/Modeling/DocumentAttribute.cs, src/Redis.OM/Modeling/RedisCollectionStateManager.cs, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisCommands.cs, src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/RediSearchTests/HashPerson.cs, test/Redis.OM.Unit.Tests/Serialization/DateTimeSerializationTest.cs, test/Redis.OM.Unit.Tests/Serialization/JsonObjectWithDateTime.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithATimestamp.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithCustomIdGenerationStrategy.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithUserDefinedId.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs, test/Redis.OM.Unit.Tests/Serialization/StaticIncrementStrategey.cs
Updating the way datetimes are serialized to/from redis for both hashes and JSON. Updating how custom Id Generation works.
=> Date time hash bug - id generation

README.md, test/Redis.OM.Test.ConsoleApp/Program.cs
I tried using the POC app and found that the Insert Object was missing. So added the same. 
This is my first pull request to an open-source.  Do let me know if there is any mistake I will correct the same. 
Also, this contribution is really small to make into contributions I can remove my name.
=> Added the Insert Object to the Example Application

LICENSE, README.md, src/Redis.OM/Redis.OM.csproj
Changing License to MIT as per @banker, this will resolve #18, License change will be effective in NuGet in the next version of the library.
=> Changing License to MIT from BSD-3 clause

README.md, src/Redis.OM/RedisObjectHandler.cs, src/Redis.OM/Uuid4IdGenerationStrategy.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithGuidId.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs
Probably fixes half of the issue in #48 and I think this will fix the issue in #51
=> fixing UUID4 generation logic, fixing id generation of value types

src/Redis.OM/Searching/IRedisCollection.cs
Adding `Any` To `IRedisCollection` to fix #44
=> Adding Any to IRedisColleciton Interface

src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ReducerTests.cs
When multiple reductions are added at the moment, multiple GROUPBY's are erroneously added, this is due to the way the expression translator peeks at and decides whether to push a groupby. In fact, with each new reduction, the groupby needs to be moved to the top of the stack so that it's the first predicate picked up when translating future reductions.
Fixes #65
=> fixing ordering of groupbys when there are multiple reducers

README.md, src/Redis.OM/RedisConnectionProvider.cs, test/Redis.OM.Test.ConsoleApp/Program.cs, test/Redis.OM.Unit.Tests/ConnectionTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs
The main goal of this pull request is to give a easy way to create different forms of connection.
- Creating a new way to instance connection provider and give the control of dependency injection, so the whoever consumes can control the resilience for the scope of connection.
=> Updating Connection Provider

src/Redis.OM/Aggregation/RedisAggregationSet.cs, src/Redis.OM/RedisConnectionProvider.cs, src/Redis.OM/SearchExtensions.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
=> configurable chunk-sizes

README.md, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/Modeling/RedisIndexingException.cs, src/Redis.OM/Modeling/RedisSchemaField.cs, src/Redis.OM/Modeling/SearchFieldAttribute.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Test.ConsoleApp/Program.cs, test/Redis.OM.Unit.Tests/Address.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ApplyFunctionTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/Person.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/SearchJsonTests/RedisJsonIndexTests.cs
Support JSON embedded object queries / indexing as well as Indexing JSON arrays.
=> Embedded objects queries & Array Indexing/Querying.

docs/README.md, src/Redis.OM.POC/Redis.OM.POC.csproj, src/Redis.OM.POC/RedisCommands.cs, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisCommands.cs, src/Redis.OM/RedisObjectHandler.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Issue with null values coming out of Redis. Redis OM not properly handling them.
Fixing find by id so that it works with ids as well as keynames.
Fixes #83
=> Fixing issue with non-existant keys in findbyid, fixing some tests for async/await pattern, removing GET from POC.

test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ReducerTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
=> cleaning getawaiters out of tests

src/Redis.OM/Modeling/DocumentAttribute.cs, src/Redis.OM/Modeling/RedisIndex.cs, src/Redis.OM/stylecop.ruleset, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithTwoStopwords.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithZeroStopwords.cs
Resolves #101 allowing you to add stopwords to your index definition.
=> adding ability to configure stopwords on an index

README.md, test/Redis.OM.Unit.Tests/RediSearchTests/RedisIndexTests.cs
Related to https://github.com/redis/redis-om-dotnet/pull/178.
* Added more test cases.
* Update contributors list to use links.
=> Add more unit test for `GetIndexInfo`

src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
=> Fix #170 to save FindById result to StateManager

README.md, src/Redis.OM/RedisCommands.cs
=> Make FindByIdAsync() work asynchronous independent of the type of T in RedisCollection class.

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #191 - issue caused by weird query language parsing issue, resolvable via proper grouping with parentheses.
=> fix issue with grouped queries

README.md, src/Redis.OM/RedisCommands.cs, test/Redis.OM.Unit.Tests/CoreTests.cs
To fix issue https://github.com/redis/redis-om-dotnet/issues/208
=> Fixed TTL Decimal to long

examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument.sln, examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Customer.cs, examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Person.cs, examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs, examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument.csproj
Closes #223 
My discord handle DevilRex#6421
Thank you.
=> Adding Delete Document Stored Example

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
this is to fix issue https://github.com/redis/redis-om-dotnet/issues/275.
=> Fixed contains for guid/ulid/enum

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
=> issue with closures messing up contains

test/Redis.OM.Unit.Tests/RediSearchTests/ObjectWithEmbeddedArrayOfObjects.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs, test/Redis.OM.Unit.Tests/SearchJsonTests/RedisJsonNestedComposeValueTest.cs
=> support for JSON.ArrIndex with none scalar value

src/Redis.OM/Redis.OM.csproj
Fixes #311 - weird I thought I had added it already - looks like I had only added it for Debug builds for some odd reason.
=> adding documentation to NuGet package

src/Redis.OM/Modeling/RedisSchemaField.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs, test/Redis.OM.Unit.Tests/Serialization/ComplexObjectWithCascadeAndJsonPath.cs
Fixes #320 - issues arose when mixing methods of embedding indexes.
=> mixed embedded object paths

docker/docker-compose.yaml, src/Redis.OM/Aggregation/AggregationResult.cs, src/Redis.OM/RedisReply.cs, src/Redis.OM/Searching/SearchResponse.cs, test/Redis.OM.Unit.Tests/CoreTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs
=> adding error propagation for non-apparent (but very real errors)

src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/Serialization/HashTypeWithPrimitiveArray.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs
=> fixing issue with serializing collections of primitives with hashes.

src/Redis.OM/Modeling/JsonDiff.cs, src/Redis.OM/Modeling/RedisCollectionStateManager.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithDateTimeOffset.cs
Fixes #280 - Date times were not being serialized correctly in the state manager
=> fixing update bug with DateTimeOffsets

README.md, src/Redis.OM/Aggregation/AggregationPredicates/QueryPredicate.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs
this is for the issue: https://github.com/redis/redis-om-dotnet/issues/392
=> allow applying of logical OR on different fields in .Where clause on aggregation set

src/Redis.OM.POC/Redis.OM.POC.csproj, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisReply.cs, test/Redis.OM.Unit.Tests/CoreTests.cs
=> updating StackExchange.Redis Version to remove System.Drawing

src/Redis.OM/RedisCommands.cs, test/Redis.OM.Unit.Tests/CoreTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/VectorTests/VectorTests.cs
Resolves #443 - specifies which arguments are keys in ad-hoc api
=> specifying keys in read/write commands

src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #489 - adding selects interferers with the multi-filter building portion of the query parser, so needed to find another way to mange it here.
=> fixing issue with multiple where predicates paired with a select

src/Redis.OM/Aggregation/AggregationPredicates/AggregateSortBy.cs, src/Redis.OM/Aggregation/AggregationPredicates/MultiSort.cs, src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/SearchExtensions.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs
Resolves #502 - adds the ability to set max in sortby (needed because the default max is 10)
=> allowing setting max in sortby

src/Redis.OM.Vectorizers.AllMiniLML6V2/Redis.OM.Vectorizers.AllMiniLML6V2.csproj, src/Redis.OM.Vectorizers.Resnet18/Redis.OM.Vectorizers.Resnet18.csproj, src/Redis.OM.Vectorizers/Redis.OM.Vectorizers.csproj, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Modeling/RedisSchemaField.cs, src/Redis.OM/Modeling/TypeDeterminationUtilities.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Unit.Tests/RediSearchTests/ObjectWithNumericArrays.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs
Adding querying for arrays of numerics in RediSearch using the same mechanism we used for strings
=> adding functionality for array querying with numerics
