redis/redis-om-dotnet

README.md, src/Redis.OM/GeoLoc.cs, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/BasicTypeWithGeoLoc.cs, test/Redis.OM.Unit.Tests/GeoLocTests.cs
Improving parsing for geolocs, making the structure not readonly so it can be sent across as JSON and bound properly, adding a missing condition in the object handler so that it is pulled correctly out of redis.
=> Improving parsing for GeoLocs

README.md
A link broke in the readme when the repo was moved from redis-developer org to the redis org. fixes #25
=> fixing broken link in readme

README.md
1. Removed the Index attribute from the `Email` property, that is to show that not all properties require to be indexed.
2. Removed the `Sortable` attribute from the `LastName` property, that is to show that not all Index attribute requires such property.
3. Adjusted the creation of the Redis index to directly access `IRedisConnection` through the `RedisConnectionProvider`.
That is to avoid confusion of not knowing how to access `IRedisConnection`
The current documentation is missing the `connection` variable creation, such as - 
var connection = provider.Connection;
As working directly on the `IRedisConnection` shouldn't be needed in such a wrapper I simply skipped that variable and used `Provider.Connection` directly.
4. Added an example of inserting a new document, that is to show that …
=> Docs adjustments

src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithIntegerId.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithStandardId.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithUlidId.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs
1. Adjusted to an easier-to-maintain types check.
2. Added Int to the supported RedisIdFieldAttribute fields, Integer sounds like a commonly used property for indexing, why would Integers not be accepted?
3. Removed non-working default check on an object type, still checking for null value although it covers only strings.
4. Removed idProperty.SetValue(obj, id) to avoid exceptions when the property is not of type string.
=> Refactoring RedisObjectHandler.SetId, Added Integer to the supported RedisIdFieldAttribute

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
There are some peculiarities when mixing scopes for compiler-generated class expressions. If everything is an in-scope local the expression will only be one member deep and have a constant expression, however, it looks like if the local is declared out of the immediate scope and you are iterating over something (e.g. a List) that the local generated by the foreach will mix with the out-of-scope local in the generated class and mess with some of the logic in the ExpressionTranslator - it looks like we can overcome this by compiling/invoking the member expression - which might be a bit slower, but definitely more predictable.
=> generalized solution for compiler generated class expressions

src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/RediSearchCommands.cs, src/Redis.OM/Searching/Query/RedisQuery.cs
I was experimenting with the code and found the search extension method which allows me to work on the low-level API. So I tried the same
``` csharp
SearchResponse<Movies> searchResponse = provider
.Connection
.Search<Movies>(new RedisQuery { QueryText = "war" });
foreach (var item in searchResponse.Documents)
{
Console.WriteLine(item.Value.Title);
}
```
I got an Argument Null exception as IndexName is one of the mandatory parameters. Since my index is automatically created by the library, I took some time to find the index pattern. 
Since we are already passing the Generics we can use the code
``` csharp 
query.Index = typeof(T).SerializeIndex().FirstOrDefault() ?? string.Empty;
```
or use the below code
``` csharp
var objAttribute = Attribute.GetCustomAttribute(
type, …
```
=> Search command Fails When the Index was missing

README.md
When browsing through the README, I noticed some of the links were based on an old code location, so I have updated those in this PR, and the PRs linked below for each repo:
redis/redis-om-dotnet#46
redis/redis-om-node#37
redis/redis-om-python/pull/95
redis/redis-om-spring#14
=> Fix old redis-developer links in README

README.md, src/Redis.OM/Modeling/GeoLocJsonConverter.cs, test/Redis.OM.Unit.Tests/GeoLocTests.cs
Made parsing of longitude and latitude values process culture independent.
Before this fix GeoLocTests.TestParsingFromFormattedHash test fails when process culture define use of comma char as decimal separator for numbers or any other char different from the dot char.
=> Fixed GeoLoc wrong parsing

src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/Serialization/ObjectWithDateTimeOffset.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs
Should fix #50 - `DateTimeOffset` was causing infinite recursive when not explicitly pulled out, saving as ISO8601 timestamp for the hash field.
=> DateTimeOffsetParsing for hash

README.md, src/Redis.OM/RediSearchCommands.cs, test/Redis.OM.Unit.Tests/RediSearchTests/RedisIndexTests.cs
Added missing exception handling to `CreateIndex`, `CreateIndexAsync` and `DropIndexAsync`
=> Exception handling for index creation/deletion

src/Redis.OM/Modeling/RedisCollectionStateManager.cs, src/Redis.OM/RedisCommands.cs, src/Redis.OM/RedisObjectHandler.cs, src/Redis.OM/Scripts.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisCollectionEnumerator.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/Person.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Adds an API to update / delete a single record at a time.
Flow for update:
case 1: the snapshot contains the record
* Compute diff between what's in the snapshot and the record
* Run script to bring the records into sync
case 2: Snapshot does not contain the record
* Run script to unlink the object, and then set the whole record.
For delete, simply find the keyname from the object and unlink it.
=> Single record updates / deletes

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixing issue with Model property access within queries, it was formatting the query strings as a path to the property rather than the value. This also removes a nasty Compile operation. 
Added new path for handling string interpolation and string formats.
Fixes issues raised in #84
=> Fixing issues with Model property access, string interpolation

src/Redis.OM/Modeling/DocumentAttributeExtensions.cs, src/Redis.OM/RediSearchCommands.cs, src/Redis.OM/RedisCommands.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Should resolve #85 
Adding the following async operations:
* First
* FirstOrDefault
* ToList
* Single
* SingleOrDefault
* Count
* Any
As there is some meaningful value to add within the RedisCollection to streamline these queries operationally. Some others are intentionally excluded, e.g. Last, which is not practical to get at without more than 1 round trip to Redis.
Adding `UpdateSync` and `DeleteSync` so there is a sync API for update & delete.
=> adding certain async collection operations

src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Original Delete/Update methods were written as purely async with DeleteSync/UpdateSync added as more or less an afterthought, remapping them to be more typical of .NET patterns. Resolves #125, This will be a breaking change, so will need to rev to 0.2.0.
=> delete/update remapping to typical sync/async pattern

src/Redis.OM/Aggregation/AggregationPredicates/AggregateSortBy.cs, src/Redis.OM/Aggregation/AggregationPredicates/MultiSort.cs, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ApplyFunctionTests.cs
This should address #113 - adds multiple-sort predicate support e.g.
`collection.OrderBy(x => x.RecordShell.Name).OrderByDescending(x => x.RecordShell.Age)`
should translate to 
`Execute("FT.AGGREGATE","person-idx", "*", "SORTBY", "4", "@Name", "ASC", "@Age", "DESC", "WITHCURSOR", "COUNT", "10000")`
Also addresses an apply expression expansion issue I stumbled over while investigating #114
=> Adding multiple-sort support, fixing apply expansion issue.

src/Redis.OM/RedisObjectHandler.cs, test/Redis.OM.Unit.Tests/Serialization/HashObjectWithTwoPropertiesWithMatchingPrefixes.cs, test/Redis.OM.Unit.Tests/Serialization/SerializationTests.cs
Fixing issue with hash hydration caused by multiple prefixes matching the property name, this is caused by the way we handle serializing collections within hashes and embedded hashes within hashes, just need to check that the property is in what's reported back from Redis. Fixes #120
=> hash parsing issue

src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/PredicateBuilder.cs, src/Redis.OM/SearchExtensions.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisCollectionEnumerator.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Addresses #78,
Allows users to build their queries in stages. Previously, Redis OM .NET would only honor the last boolean query passed to it. So if you queried
```
collection.Where(x=>x.FirstName == "Alice").First(x=>x.Age < 32);
```
Only all the people younger than 32 would be returned from the collection. With this PR, both queries are cleanly folded together to make one query to Redis.
The methodology for this is that the collection now keeps track of all `Expression<Func<T,bool>>` passed to it over time, folding them all together into something usable.
=> adding the ability to build queries in stages

src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Adds FindByIdAsync, solves #96 - explicitly does not add a non-async version due to pipelining concerns.
=> Adding FindByIdsAsync

docker/dotnet/dockerfile, dockerfile, test/Redis.OM.Test.AspDotnetCore/Redis.OM.Test.AspDotnetCore.csproj, test/Redis.OM.Test.ConsoleApp/Redis.OM.Test.ConsoleApp.csproj, test/Redis.OM.Unit.Tests/Redis.OM.Unit.Tests.csproj
Since .NET is already [out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle), how about upgrading the test project to use .NET 6?
Feel free to give any feedback about these changes.
=> Update Test Project to .NET 6

src/Redis.OM/RedisConnectionProvider.cs, src/Redis.OM/SearchExtensions.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisCollectionEnumerator.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
#189 points out an important point, many folks will not want the StateManager to maintain any of their records, whether this is because of the concurrency issues that are pointed out in there, or they just don't want very large collections of data initalized under the hood, giving folks the ability to configure this will be pretty helpful. Adding new path to allow users to decide whether or not to have said data stored.
=> allows users to not save enumerated data in the StateManager

src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #201 - issue propagated when adding the inverted contains queries, when a search attribute is found on a property you are trying to search on. Adding a check to see if a literal value can be derived from the property being searched on prior to generating the query.
=> fixing backwards contains queries.

src/Redis.OM/Aggregation/RedisAggregationSet.cs, src/Redis.OM/Searching/RedisCollection.cs, src/Redis.OM/Searching/RedisQueryProvider.cs
Fixes #205, adding better exception handling for folks who try enumerating the same redis collection twice. @VagyokC4 - can you check this to make sure this fixes your issue :)
=> fixing other stateful queries issue

src/Redis.OM.POC/RedisCommands.cs
This will resolve #214, the APIs being moved to internal here were never intended for public consumption, they were meant to load and execute the highly specialized update scripts that I wrote for executing minimal updates against redis. This will constitute a minor breaking change to Redis OM, and will therefore require the version bearing it to rev to v0.3.0.
=> moving stuff for internal scripts to internal

src/Redis.OM/Redis.OM.csproj
Revving to 0.3.0 for release (minor breaking change brought on by #225 - as those APIs should never have been public in the first place :)
=> revving 0.3.0

src/Redis.OM.Analyzer/Redis.OM.Analyzer.csproj, src/Redis.OM/Aggregation/AggregationPredicates/AggregateSortBy.cs, src/Redis.OM/Aggregation/AggregationPredicates/ApplyFunctions.cs, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/GeoLoc.cs, src/Redis.OM/RedisReply.cs, src/Redis.OM/SearchExtensions.cs, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/GeoLocTests.cs, test/Redis.OM.Unit.Tests/Helper.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ApplyFunctionTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ReducerTests.cs
This PR fixes all tests that fails when executed in an environment using a culture where the decimal number separator character isn't a dot char (e.g. it-IT, fr-FR, etc.).
For any failing test I've added a namesake one with the suffix "TestingInvariantCultureCompliance" where test runs on different process culture.
=> Enforced culture invariant compliance

README.md, src/Redis.OM/GeoLoc.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Unit.Tests/GeoLocTests.cs
GeoLoc.ToString() doesn't produce a stable output if the culture changes.
This PR fixes that - see #229
=> Bugfix for GeoLoc Serialization in Different Cultures

examples/Redis.OM.LowLevelSearchIndex/Helpers/RedisHelper.cs, examples/Redis.OM.LowLevelSearchIndex/Models/Customer.cs, examples/Redis.OM.LowLevelSearchIndex/Program.cs, examples/Redis.OM.LowLevelSearchIndex/Redis.OM.LowLevelSearchIndex.csproj
=> Add low level search example

README.md, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/Modeling/DateTimeJsonConverter.cs, src/Redis.OM/Modeling/TypeDeterminationUtilities.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Unit.Tests/RediSearchTests/ObjectWithDateTime.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs
Adds ability to index and query DateTimes in Redis with Redis OM, this will be a SOMEWHAT breaking change, because the mode of storage of DateTimes in Redis is changing from strings to numerics, this shouldn't effect anyone only working in Redis OM and interacting with said datetimes because the JSON parser is setup to handle both cases, but all the same it's changing the behavior at storage, so I'm revving to 0.4.0
=> adding ability to index and query datetimes

src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Close #238 - Adding a feature to Bulk Insert data into Redis with the help of pipelines.
=> adding bulkinsert support

examples/Redis.OM.FullTextSearch/Program.cs, examples/Redis.OM.FullTextSearch/RedisHelper/RedisHelper.cs, src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #203, issue with `List` type queries the expression object not parsing inverted contains.
=> fix:backward-contains-list-type-queries

README.md, src/Redis.OM.AspNetCore/ServiceCollectionExtensions.cs, src/Redis.OM/Contracts/IRedisConnectionProvider.cs, src/Redis.OM/RedisConnectionProvider.cs
=> IRedisConnectionProvider interface

src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #243 - forgot to add `Any()` to IRedisColleciton, so it defaulted to the Query Providers Execute method.
=> Adding Any method without arguments to IRedisCollection

src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisCommands.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #272 - issue is when redis is rolled over, the client's not properly handling the reload and trying to send `EVALSHA`'s when it really needs to either run an `EVAL` or script reload. Because At this point in the error flow we are already one or two round trips to redis in, we'll use an `EVAL` for the initial condition, and empty out our collection of SHA's so that we force the client to reload all scripts it was previously running
=> forcing reload on scripting error, using correct sha in some tests

src/Redis.OM/RedisCommands.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/BulkOperationsTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
**Adding feature to Redis-om-dotnet where developers can perform Bulk Operations like Insert, Delete, and Update.**
=> feature: Bulk Operations 

src/Redis.OM/Modeling/RedisCollectionStateManager.cs, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisCommands.cs, src/Redis.OM/RedisObjectHandler.cs, src/Redis.OM/Scripts.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/CoreTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/BulkOperationsTests.cs
There's some lurking race's going on within Redis OM, particularly when it comes to highly parallelized async operations (e.g. bulk update / fetch).
Two primary culprits:
1. The dictionary we're using to hold the scripts sha's are not thread-safe, so if the sha collection was updated while also being read, the dictionary was throwing an invalid operation exception.
2. The Bulk Update/FindById async methods both leverage their respective non-bulk versions. Which would be fine if not for the fact that they both update the State Manager, since the state manager is not meant to be thread-safe, when multiple async tasks hit it simultaneously, all sorts of unpredictable things can happen. 
This PR addresses both of these issue.
=> Fixing races

src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #289 and #291 which are both caused by separate instances of us not tearing down the path to nested objects correctly in their respective predicates
=> fixing paths to nested objects in various predicates

src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/ObjectWithStringLikeValueTypes.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #309 - Not properly finding underpinning types of Nullable Enums - extracting type when building queries.
=> fixing nullable enum parsing

src/Redis.OM/Common/ExpressionTranslator.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #307 - When implementing #157 - removed the `Where` parsing because the boolean expression was being fully parsed below, if someone uses a `SELECT` however, all that context is lost - bringing it back.
=> adding back context for lost where clauses

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs
Fixes #317 
The fundamental issue is that binary expressions weren't being detected correctly, so when it was joining everything together the expression translator was pushing parsed expressions onto the stack erroneously
=> fixing bin expression detection

src/Redis.OM/Modeling/JsonDiff.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RedisSetupCollection.cs, test/Redis.OM.Unit.Tests/Serialization/BasicJsonObject.cs
=> JavaScriptEncode for update diff

src/Redis.OM/RedisReply.cs
I re-enabled warnings as errors (accidentally removed it) and one of my PRs didn't fully comply with Style-Cop's rules - fixing.
=> fixing style-cop violation

src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/Redis.OM.csproj, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/Serialization/SelectTestObject.cs
Fixes #371 - decision to not alias if field name was the same in the object being projected onto as the initial object was apparently ill-advised as it was making it impossible to parse correctly.
=> fixing selects with same names

src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Modeling/RedisSchemaField.cs
There is a problem when using [Indexed] `List<Guid>` right now - index for them is not created, and querying is not working. This will fix this.
However, as I can see right now, current aprroach is quite bad - you have to manually add new types and it's possible to forget to add it in one place or another. 
And I had to spend a few hours to find out, why `List<Guid>` is not working, there was no indication from RedisOM that I'm doing something wrong.
Also, you probably can't cover all types, that can be indexed: user can use for indexing any signle-line field (DateTime, DateTimeOffset, Enum, Uri, and the list goes on, not to mention it's possible to create custom types). All these types can be serialized as valid JSON single-line fields (string or number)
So, you need to check not the …
=> Fix indexing and querying GUID lists

README.md, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/Searching/RedisCollectionEnumerator.cs, src/Redis.OM/Searching/SearchResponse.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Addresses bug found in #421 i.e. enumerating a collection from a search where the documents were expiring causes an early return resulting in less documents than expected.
@slorello89 Side note - I noticed that the non-generic [SearchResponse](https://github.com/redis/redis-om-dotnet/blob/fa80a84bb141ab0b6ff44fdf8f2a5e59a8120aee/src/Redis.OM/Searching/SearchResponse.cs#L11) would [return an empty Document](https://github.com/redis/redis-om-dotnet/blob/fa80a84bb141ab0b6ff44fdf8f2a5e59a8120aee/src/Redis.OM/Searching/SearchResponse.cs#L25C1-L32C52) i.e. an empty dictionary documentHash, akin to returning null. But the generic `SearchResponse<T>` just skips the document instead. In the same vein, [AggregationResult](https://github.com/redis/redis-om-dotnet/blob/fa80a84bb141ab0b6ff44fdf8f2a5e59 …
=> Bugfix - Enumerating collection with documents expiring causes early return

src/Redis.OM.Vectorizers.AllMiniLML6V2/Redis.OM.Vectorizers.AllMiniLML6V2.csproj, src/Redis.OM.Vectorizers.Resnet18/Redis.OM.Vectorizers.Resnet18.csproj, src/Redis.OM.Vectorizers/Redis.OM.Vectorizers.csproj, src/Redis.OM/Redis.OM.csproj, src/Redis.OM/RedisCommands.cs, test/Redis.OM.Unit.Tests/CoreTests.cs
Fixes #433
Unlink should return a long not a string (it does not get cast correctly). technically a breaking change so updating version as well.
=> correcting unlink return type

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs
Need to make sure that filter formatting is passed down recursively when splitting binary expressions to ensure that strings are properly formatted for filter expressions in aggregations.
=> passing filter format down Fixes #438

CONTRIBUTING.md, README.md, src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Vectorizer.Tests/VectorizerFunctionalTests.cs
When trying to use a `VectorRange` query using a non-constant value, an exception is thrown:
```
Exception has occurred: CLR/System.InvalidCastException
Exception thrown: 'System.InvalidCastException' in Redis.OM.dll: 'Unable to cast object of type 'System.Linq.Expressions.UnaryExpression' to type 'System.Linq.Expressions.ConstantExpression'.'
at Redis.OM.Common.ExpressionParserUtilities.TranslateVectorRange(MethodCallExpression exp, List`1 parameters)
at Redis.OM.Common.ExpressionParserUtilities.TranslateMethodExpressions(MethodCallExpression exp, List`1 parameters)
at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression exp, List`1 parameters)
at Redis.OM.Common.ExpressionTranslator.TranslateWhereMethod(MethodCallExpression expression, List`1 parameters)
at …
```
=> Improved vector range argument parsing

README.md, src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Solves #441, where `Any()` for embedded objects does not support method call expressions (e.g. `Contains()`, `StartsWith()` etc.). So, in addition to `BinaryExpression `translation support, added the handling of `MethodCallExpression `case. So, it would allow such constructions as, for example: `collection.Where(x => x.EmbeddedCollection.Any(a => a.Property.Contains("Value")))`. Previously, only basic BinaryExpressions like the equality check '==' were allowed.
=> Bugfix: support method call in Any() on embedded objects array

src/Redis.OM.POC/Redis.OM.POC.csproj, src/Redis.OM/Redis.OM.csproj
Bumping System.Text.Json version because of [CVE](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w)
=> bumping System.Text.Json for cve

README.md, src/Redis.OM/Searching/RedisQueryProvider.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Casting IRedisCollection to IQueryable no longer drops chunk size info for pagination.
Closes https://github.com/redis/redis-om-dotnet/issues/454
=> fix: Casting to IQueryable no longer drops chunk size

README.md, src/Redis.OM/Modeling/RedisIndex.cs
Fix typo/bug in index serialization and creation which serializes `LanguageField` to `Language` instead of `Language_Field`
=> Fix Typo LANGUAGE_FIELD->LANGUAGE in SerializeIndex

src/Redis.OM/RedisCommands.cs, src/Redis.OM/Scripts.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Closes #430, adding the ability to set a ttl when updating
=> feat: adding the ability to update ttl with update

README.md, src/Redis.OM/Common/ExpressionParserUtilities.cs, src/Redis.OM/Extensions/StringExtension.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Add `MatchPattern `method to enhances the search functionality by supporting pattern-based matching
=> Add MatchPattern Method

.github/workflows/dotnet-core.yml, README.md, src/Redis.OM/Modeling/RedisIndex.cs, src/Redis.OM/RediSearchCommands.cs, test/Redis.OM.Unit.Tests/RediSearchTests/RedisIndexTests.cs
Hi @slorello89,
This PR adds support to be able to have a _VERY_ simple mechanism for the consumer of the library to determine if they need to drop/recreate a given index.
I foresee people using this method like this pseudocode Index drop/create is async I believe, so the consumer would need to do their own polling to wait for the index to properly delete first but:
```csharp
var provider = new RedisConnectionProvider("redis://localhost:6379");
var definition = provider.Connection.GetIndexInfo(typeof(Customer));
if (definition.IndexDefinitionEquals(typeof(Customer)) == false)
{
provider.Connection.DropIndex(typeof(Customer));
}
provider.Connection.CreateIndex(typeof(Customer));
```
Please forgive me that I've not raised an issue for this beforehand - I'm hoping this PR makes enough sense …
=> feat: Add the ability to compare existing index definitions to the projected one for a type

README.md, src/Redis.OM/Aggregation/RedisAggregationSet.cs, src/Redis.OM/Searching/IRedisCollection.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationSetTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Exposes ToQueryString from RedisCollection and RedisAggregationSet.
Resolves #486
The following questions came up while putting this together:
1. Is `ToQueryString` a reasonable name? Is `ToCommandString` more accurate for Redisearch?
2. These methods duplicate behavior found in `AggregationEnumerator.SerializedArgs` and `RedisCollectionEnumerator.RedisCollectionEnumerator`. Is that reasonable, or should there be a common source for that behavior?
3. Should the tests cover less RedisCollection/RedisAggregationSet behavior and just do the least amount necessary to serialize the command to a string?
=> Add ToQueryString method to RedisCollection, RedisAggregationSet

src/Redis.OM/Common/ExpressionParserUtilities.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #481 - issue was that one of the methods that breaks down matching queries was not set up to handle the new match methods.
=> fixing multiple match predicates query parsing issue

src/Redis.OM/Extensions/TimespanExtensions.cs, src/Redis.OM/RedisCommands.cs, src/Redis.OM/Searching/RedisCollection.cs, test/Redis.OM.Unit.Tests/CoreTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Fixes issues with timespans having fractional milliseconds values. Came up in a response to #430. Timespans have a TotalMilliseconds which is a double and was not properly rounded when it was fractional.
=> fixing issue with timespans having fractional millisecond values

src/Redis.OM/Modeling/RedisCollectionStateManager.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
Fixes #504 
We recently fixed an issue with DateTime's / DateTimeOffsets not being properly serialized in `Update` so they were coming up as false positives, unfortunately that does not appear to have propagated over to the `Save` feature. This PR normalizes those serialization settings, so that should not happen anymore.
=> normalizing json serialization settings in statemanager

README.md, examples/Redis.OM.RawQueryExample/Program.cs, examples/Redis.OM.RawQueryExample/Redis.OM.RawQueryExample.csproj, src/Redis.OM/Aggregation/RedisAggregation.cs, src/Redis.OM/Common/ExpressionTranslator.cs, src/Redis.OM/SearchExtensions.cs, test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/RawQueryTests.cs, test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
We've had many instances where folks have asked for Redis Queries that are difficult (or impossible) to express in the LINQ language, this PR adds support for writing raw filters in the Redis Query Language, while still supporting the Object Mapping / other LINQ bits of Redis OM.
=> FIELDENG-681 adding api for running raw queries

README.md, src/Redis.OM/RedisObjectHandler.cs
Resolves #518, addressing a JSON deserialization issue relating to a discrepancy in the return value from FT.SEARCH when the result is projected; this issue was affecting GraphQL and OData queries, although was not limited to these use cases.
=> Fix edge-case boolean deserialization in RedisObjectHandler.SendToJson
